"""Щиты (slot=shield). 16 предметов: 4 free + 4 gold + 4 dia + 4 mythic.

Этап 3B редизайна — чистый перенос из db_schema/equipment_catalog.py.
Числа НЕ менялись.
"""
from __future__ import annotations

SHIELDS: dict[str, dict] = {
    "shield_free1": {"slot": "shield", "rarity": "common", "name": "Щит Ополченца",     "emoji": "🛡️", "def_pct": 0.03, "str_bonus": 2, "price_gold": 800, "tier": "T1", "power_score": 27, "recommended_level": 1, "currency": "gold", "desc": "-3% урона врага, +2 Сила"},
    "shield_free2": {"slot": "shield", "rarity": "common", "name": "Щит Стойкости",     "emoji": "🛡️", "hp_bonus": 50,  "agi_bonus": 2, "price_gold": 800, "tier": "T1", "power_score": 27, "recommended_level": 1, "currency": "gold", "desc": "+50 HP, +2 Ловкость"},
    "shield_free3": {"slot": "shield", "rarity": "common", "name": "Щит Закалённого",   "emoji": "🛡️", "crit_resist_pct": 10, "intu_bonus": 2, "price_gold": 800, "tier": "T1", "power_score": 27, "recommended_level": 1, "currency": "gold", "desc": "-10% крит-урон врага, +2 Интуиция"},
    "shield_free4": {"slot": "shield", "rarity": "common", "name": "Щит Дружинника",    "emoji": "🛡️", "def_pct": 0.02, "hp_bonus": 30, "str_bonus": 2, "price_gold": 800, "tier": "T1", "power_score": 27, "recommended_level": 1, "currency": "gold", "desc": "-2% урона, +30 HP, +2 Сила"},
    "shield_gold1": {"slot": "shield", "rarity": "rare", "name": "Рыцарский Щит",       "emoji": "🛡️", "def_pct": 0.06, "str_bonus": 1, "agi_bonus": 1, "intu_bonus": 1, "price_gold": 8000, "tier": "T2", "power_score": 59, "recommended_level": 20, "currency": "gold", "desc": "-6% урона врага, +1 ко всем статам"},
    "shield_gold2": {"slot": "shield", "rarity": "rare", "name": "Щит Великана",        "emoji": "🛡️", "hp_bonus": 110, "str_bonus": 1, "agi_bonus": 1, "intu_bonus": 1, "price_gold": 8000, "tier": "T2", "power_score": 59, "recommended_level": 20, "currency": "gold", "desc": "+110 HP, +1 ко всем статам"},
    "shield_gold3": {"slot": "shield", "rarity": "rare", "name": "Щит Паладина",        "emoji": "🛡️", "crit_resist_pct": 18, "str_bonus": 1, "agi_bonus": 1, "intu_bonus": 1, "price_gold": 8000, "tier": "T2", "power_score": 59, "recommended_level": 20, "currency": "gold", "desc": "-18% крит-урон врага, +1 ко всем статам"},
    "shield_gold4": {"slot": "shield", "rarity": "rare", "name": "Щит Хранителя",       "emoji": "🛡️", "def_pct": 0.04, "hp_bonus": 60, "crit_resist_pct": 8, "str_bonus": 1, "agi_bonus": 1, "intu_bonus": 1, "price_gold": 8000, "tier": "T2", "power_score": 59, "recommended_level": 20, "currency": "gold", "desc": "-4% урона, +60 HP, -8% крит, +1 ко всем статам"},
    "shield_dia1":  {"slot": "shield", "rarity": "epic", "name": "Щит Дракона",         "emoji": "🛡️", "def_pct": 0.10, "str_bonus": 2, "agi_bonus": 2, "intu_bonus": 2, "price_diamonds": 75, "tier": "T3", "power_score": 3.0, "recommended_level": 45, "currency": "diamond", "desc": "-10% урона врага, +2 ко всем статам"},
    "shield_dia2":  {"slot": "shield", "rarity": "epic", "name": "Щит Колосса",         "emoji": "🛡️", "hp_bonus": 200, "str_bonus": 2, "agi_bonus": 2, "intu_bonus": 2, "price_diamonds": 75, "tier": "T3", "power_score": 3.0, "recommended_level": 45, "currency": "diamond", "desc": "+200 HP, +2 ко всем статам"},
    "shield_dia3":  {"slot": "shield", "rarity": "epic", "name": "Щит Непоколебимого",  "emoji": "🛡️", "crit_resist_pct": 25, "str_bonus": 2, "agi_bonus": 2, "intu_bonus": 2, "price_diamonds": 75, "tier": "T3", "power_score": 3.0, "recommended_level": 45, "currency": "diamond", "desc": "-25% крит-урон врага, +2 ко всем статам"},
    "shield_dia4":  {"slot": "shield", "rarity": "epic", "name": "Щит Арканы",          "emoji": "🛡️", "def_pct": 0.07, "hp_bonus": 90, "crit_resist_pct": 12, "str_bonus": 2, "agi_bonus": 2, "intu_bonus": 2, "price_diamonds": 75, "tier": "T3", "power_score": 3.0, "recommended_level": 45, "currency": "diamond", "desc": "-7% урона, +90 HP, -12% крит, +2 ко всем статам"},
    "shield_mythic1": {"slot": "shield", "rarity": "mythic", "name": "Щит Судьбы",       "emoji": "🛡️", "def_pct": 0.14, "hp_bonus": 160, "str_bonus": 4, "agi_bonus": 4, "intu_bonus": 4, "price_stars": 590, "tier": "T4", "power_score": 3.58, "recommended_level": 65, "currency": "star", "desc": "-14% урона, +160 HP, +4 ко всем статам"},
    "shield_mythic2": {"slot": "shield", "rarity": "mythic", "name": "Щит Бессмертного", "emoji": "🛡️", "hp_bonus": 300, "crit_resist_pct": 20, "str_bonus": 4, "agi_bonus": 4, "intu_bonus": 4, "price_stars": 590, "tier": "T4", "power_score": 3.58, "recommended_level": 65, "currency": "star", "desc": "+300 HP, -20% крит-урон, +4 ко всем статам"},
    "shield_mythic3": {"slot": "shield", "rarity": "mythic", "name": "Щит Рока",         "emoji": "🛡️", "def_pct": 0.08, "crit_resist_pct": 30, "str_bonus": 4, "agi_bonus": 4, "intu_bonus": 4, "price_stars": 590, "tier": "T4", "power_score": 3.58, "recommended_level": 65, "currency": "star", "desc": "-8% урона, -30% крит-урон, +4 ко всем статам"},
    "shield_mythic4": {"slot": "shield", "rarity": "mythic", "name": "Щит Богов",        "emoji": "🛡️", "def_pct": 0.10, "hp_bonus": 120, "crit_resist_pct": 18, "str_bonus": 4, "agi_bonus": 4, "intu_bonus": 4, "price_stars": 590, "tier": "T4", "power_score": 3.58, "recommended_level": 65, "currency": "star", "desc": "-10% урона, +120 HP, -18% крит, +4 ко всем статам"},
}
